{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-18T08:26:17.336Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-18T08:26:17.342Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-18T08:26:18.503Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-18T08:26:18.506Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-18T08:26:19.782Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-18T08:26:19.786Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-18T08:26:21.228Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-18T08:26:21.232Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-18T08:26:24.162Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-18T08:26:24.169Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-18T08:26:31.827Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-18T08:26:31.830Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-18T08:26:33.011Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-18T08:26:33.013Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-18T08:26:34.095Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-18T08:26:34.101Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-18T08:26:35.216Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-18T08:26:35.218Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-18T08:26:38.185Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-18T08:26:38.189Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-18T08:26:41.393Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-18T08:26:41.395Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-18T08:26:42.414Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-18T08:26:42.416Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-18T08:26:43.568Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\oldprojects\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-18T08:26:43.572Z"}
{"error":{"code":101,"message":"Invalid username/password."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Invalid username/password.' }","timestamp":"2018-05-18T10:54:21.397Z"}
{"code":101,"message":"Invalid username/password.","level":"error","timestamp":"2018-05-18T10:54:21.401Z"}
{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-18T10:57:09.155Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-18T10:57:09.156Z"}
{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-18T10:57:20.579Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-18T10:57:20.582Z"}
{"error":"PushController: no results in query","level":"error","message":"_PushStatus Rp5WC7F8ry: error while sending push","timestamp":"2018-05-18T10:58:33.768Z"}
{"error":"PushController: no results in query","level":"error","message":"_PushStatus nTuX9yvLVX: error while sending push","timestamp":"2018-05-18T11:37:41.776Z"}
{"error":"PushController: no results in query","level":"error","message":"_PushStatus FDE3en7E8F: error while sending push","timestamp":"2018-05-18T12:55:15.532Z"}
{"error":"PushController: no results in query","level":"error","message":"_PushStatus C8Nnz0OIIz: error while sending push","timestamp":"2018-05-18T14:10:40.624Z"}
