{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-02T05:13:16.969Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-02T05:13:16.974Z"}
{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-02T05:14:52.762Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-02T05:14:52.763Z"}
{"error":{"code":201,"message":"password is required."},"level":"error","message":"Error handling request: ParseError { code: 201, message: 'password is required.' }","timestamp":"2018-05-02T05:14:52.789Z"}
{"code":201,"message":"password is required.","level":"error","timestamp":"2018-05-02T05:14:52.791Z"}
{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-02T05:15:03.030Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-02T05:15:03.031Z"}
{"error":{"code":101,"message":"Invalid username/password."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Invalid username/password.' }","timestamp":"2018-05-02T05:15:03.904Z"}
{"code":101,"message":"Invalid username/password.","level":"error","timestamp":"2018-05-02T05:15:03.906Z"}
{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-02T05:15:26.445Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-02T05:15:26.447Z"}
{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-02T05:15:34.365Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-02T05:15:34.367Z"}
{"error":{"code":101,"message":"Invalid username/password."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Invalid username/password.' }","timestamp":"2018-05-02T05:15:34.372Z"}
{"code":101,"message":"Invalid username/password.","level":"error","timestamp":"2018-05-02T05:15:34.372Z"}
{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-02T05:17:45.177Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-02T05:17:45.179Z"}
{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-02T05:17:51.841Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-02T05:17:51.843Z"}
{"error":{"code":101,"message":"Invalid username/password."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Invalid username/password.' }","timestamp":"2018-05-02T05:17:51.848Z"}
{"code":101,"message":"Invalid username/password.","level":"error","timestamp":"2018-05-02T05:17:51.849Z"}
{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-02T05:17:57.307Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-02T05:17:57.309Z"}
{"error":{"code":101,"message":"Invalid username/password."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Invalid username/password.' }","timestamp":"2018-05-02T05:17:57.315Z"}
{"code":101,"message":"Invalid username/password.","level":"error","timestamp":"2018-05-02T05:17:57.316Z"}
{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-02T05:18:45.555Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-02T05:18:45.556Z"}
{"error":{"code":202,"message":"Account already exists for this username."},"level":"error","message":"Error generating response. ParseError {\n  code: 202,\n  message: 'Account already exists for this username.' }","timestamp":"2018-05-02T05:19:54.275Z"}
{"code":202,"message":"Account already exists for this username.","level":"error","timestamp":"2018-05-02T05:19:54.276Z"}
{"functionName":"saveUser","error":{"code":141,"message":"Account already exists for this username."},"params":{"data":{"isActive":true,"username":"ali@ali.com","password":"123456","photo":{"_name":"22314bd3dc77dbdd6fd77e5e4738dfab_file.png","_url":"http://localhost:1337/parse/files/myAppId/22314bd3dc77dbdd6fd77e5e4738dfab_file.png"},"name":"aa","email":"aaa@aa.com","phone":"071212"}},"user":"jZLxqIirxY","level":"error","message":"Failed running cloud function saveUser for user jZLxqIirxY with:\n  Input: {\"data\":{\"isActive\":true,\"username\":\"ali@ali.com\",\"password\":\"********\",\"photo\":{\"__type\":\"File\",\"name\":\"22314bd3dc77dbdd6fd77e5e4738dfab_file.png\",\"url\":\"http://localhost:1337/parse/files/myAppId/22314bd3dc77dbdd6fd77e5e4738dfab_file.png\"},\"name\":\"aa\",\"email\":\"aaa@aa.com\",\"phone\":\"071212\"}}\n  Error: {\"code\":141,\"message\":\"Account already exists for this username.\"}","timestamp":"2018-05-02T05:19:54.278Z"}
{"error":{"code":141,"message":"Account already exists for this username."},"level":"error","message":"Error generating response. ParseError {\n  code: 141,\n  message: 'Account already exists for this username.' }","timestamp":"2018-05-02T05:19:54.278Z"}
{"code":141,"message":"Account already exists for this username.","level":"error","timestamp":"2018-05-02T05:19:54.279Z"}
{"error":{"code":202,"message":"Account already exists for this username."},"level":"error","message":"Error generating response. ParseError {\n  code: 202,\n  message: 'Account already exists for this username.' }","timestamp":"2018-05-02T05:19:59.722Z"}
{"code":202,"message":"Account already exists for this username.","level":"error","timestamp":"2018-05-02T05:19:59.724Z"}
{"functionName":"saveUser","error":{"code":141,"message":"Account already exists for this username."},"params":{"data":{"isActive":true,"username":"ali@ali.com","password":"123456","photo":{"_name":"22314bd3dc77dbdd6fd77e5e4738dfab_file.png","_url":"http://localhost:1337/parse/files/myAppId/22314bd3dc77dbdd6fd77e5e4738dfab_file.png"},"name":"aaasdasdas","email":"aaa@aa.com","phone":"071212"}},"user":"jZLxqIirxY","level":"error","message":"Failed running cloud function saveUser for user jZLxqIirxY with:\n  Input: {\"data\":{\"isActive\":true,\"username\":\"ali@ali.com\",\"password\":\"********\",\"photo\":{\"__type\":\"File\",\"name\":\"22314bd3dc77dbdd6fd77e5e4738dfab_file.png\",\"url\":\"http://localhost:1337/parse/files/myAppId/22314bd3dc77dbdd6fd77e5e4738dfab_file.png\"},\"name\":\"aaasdasdas\",\"email\":\"aaa@aa.com\",\"phone\":\"071212\"}}\n  Error: {\"code\":141,\"message\":\"Account already exists for this username.\"}","timestamp":"2018-05-02T05:19:59.725Z"}
{"error":{"code":141,"message":"Account already exists for this username."},"level":"error","message":"Error generating response. ParseError {\n  code: 141,\n  message: 'Account already exists for this username.' }","timestamp":"2018-05-02T05:19:59.726Z"}
{"code":141,"message":"Account already exists for this username.","level":"error","timestamp":"2018-05-02T05:19:59.727Z"}
{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-02T05:25:58.709Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-02T05:25:58.711Z"}
{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-02T05:26:00.300Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-02T05:26:00.302Z"}
{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-02T05:26:09.079Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-02T05:26:09.081Z"}
{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-02T05:33:58.358Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-02T05:33:58.362Z"}
{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-02T13:32:31.637Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-02T13:32:31.641Z"}
{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-02T13:32:37.504Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-02T13:32:37.508Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T13:32:38.699Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T13:32:38.702Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T13:32:39.931Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T13:32:39.935Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T13:32:41.106Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T13:32:41.108Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T13:32:42.553Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T13:32:42.556Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T13:32:45.000Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T13:32:45.002Z"}
{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-02T13:33:05.040Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-02T13:33:05.042Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T13:33:06.050Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T13:33:06.055Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T13:33:07.170Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T13:33:07.173Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T13:33:08.510Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T13:33:08.513Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T13:33:09.558Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T13:33:09.559Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }","timestamp":"2018-05-02T13:33:11.041Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' } MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\topologies\\server.js:336:35)\n    at Pool.emit (events.js:160:13)\n    at Connection.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\pool.js:280:12)\n    at Object.onceWrapper (events.js:255:19)\n    at Connection.emit (events.js:160:13)\n    at Socket.<anonymous> (C:\\xampp\\htdocs\\resturantapp\\RestaurantAdmin\\node_modules\\mongodb-core\\lib\\connection\\connection.js:187:49)\n    at Object.onceWrapper (events.js:255:19)\n    at Socket.emit (events.js:160:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","timestamp":"2018-05-02T13:33:11.044Z"}
{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-02T13:34:46.400Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-02T13:34:46.402Z"}
{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-02T13:38:46.890Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-02T13:38:46.893Z"}
{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-02T13:38:50.808Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-02T13:38:50.810Z"}
{"error":{"code":209,"message":"invalid session token"},"level":"error","message":"Error handling request: ParseError { code: 209, message: 'invalid session token' }","timestamp":"2018-05-02T13:38:54.490Z"}
{"code":209,"message":"invalid session token","level":"error","timestamp":"2018-05-02T13:38:54.491Z"}
